"""init

Revision ID: 643ecb69f264
Revises: 
Create Date: 2025-12-22 18:43:12.351957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '643ecb69f264'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='原始内容'),
    sa.Column('translated_content', sa.Text(), nullable=False, comment='翻译结果'),
    sa.Column('direction', sa.String(length=20), nullable=False, comment='翻译方向: pm_to_dev / dev_to_pm'),
    sa.Column('detected_perspective', sa.String(length=20), nullable=True, comment='识别的视角: pm / dev / unknown'),
    sa.Column('gaps_identified', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='识别的缺失信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###
